name = "SpatialDatasets"
uuid = "c34fe46e-cbfb-4865-a11c-95c0a2f62188"
authors = ["Javier Barbero and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"

[compat]
DataFrames = "1"
Shapefile = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
