name = "SpatialDatasets"
uuid = "c34fe46e-cbfb-4865-a11c-95c0a2f62188"
authors = ["Javier Barbero and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
